version: '2.4'
services:
  markdown-blog-app:
    container_name: markdown-blog-app
    build: .
    ports:
      - 3000:3000
    networks:
      - mongo-network
    depends_on:
      - mongodb
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-network
volumes:
  mongodb-data:
    driver: local
networks:
  mongo-network:
    name: mongo-network
    driver: bridge